from difflib import SequenceMatcher


genres = ["Nép- és egyházi", "Klasszikus", "Ragtime és Jazz", "Alkalmazott zene", "Blues és country",
          "Rock & Roll és Beat", "Rock és Hard Rock", "Punk és New Wave", "Ezerféle Metál", "Soul és R & B",
          "Funk és Disco", "Pop(?)", "Hip-Hop", "Europop", "Kísérleti, Electro, IDM", "Techno, House, Garage",
          "Dance, Trance", "Synthpop", "Breakbeat", "EBM, Industrial", "Downtempo", "Latin nyelvterület",
          "Karib térség és Afrika", "Reggae és Ska", "Hazai pályán", "Iszlám világ", "Worldbeat és Neofolk",
          "Progresszív és Indie", "Pop és Rock fúziók", "Jazz és Swing fúziók", "Metál fúziók", "Komédia",
          "A legújabb hullám"]


artists = ["", "", "", "", "", "", "", "", "The Irish Rovers", "Szörényi Levente", "Ágnes & Kowalsky",
           "Trio Mandili", "Hildegard von Blingin", "Bach", "Franz Joseph Haydn", "Mozart", "Beethoven",
           "Bizet", "Ravel", "Mendelssohn", "Johannes Brahms", "Carl Orff", "Verdi", "Franz Liszt",
           "Francisco Tárrega", "Seress Rezső", "Scott Joplin", "Ella Fitzgerald and Duke Ellington",
           "Louis Armstrong", "Frank Sinatra", "Chordettes", "Zalatnay Sarolta", "Champs",
           "Françoise Hardy", "Quincy Jones", "Astrud Gilberto and Stan Getz",
           "Felföldi Anikó, Németh Lehel", "Vámosi János", "Fekete Pál", "Claude Joseph Rouget de Lisle",
           "Bresztovszky Ernő", "Judy Garland", "Ennio Morricone", "Harold Faltermeyer", "Tenacious D",
           "Halász Judit", "Koncz Zsuzsa", "Hidas Frigyes", "Presser Gábor", "Kid Baltan", "Tim Carleton",
           "Brian Eno", "Muddy Waters", "Johnny Cash", "Skorpió", "Fonográf", "Chris Rea", "Joe Cocker",
           "Charlie", "Edda", "Bon Jovi", "Hobo Blues Band", "Status Quo", "Sprint", "Jackyl",
           "Bill Haley And His Comets", "Chuck Berry", "Elvis Presley", "Hungária", "Beatles", "Hair",
           "Monkees", "Bergendy", "Omega", "Animals", "Mamas & The Papas", "Beach Boys", "Szandi",
           "Billy Joel", "Rolling Stones", "Soul Asylum", "Kft", "The Rembrandts", "Pat Benatar",
           "Mötley Crüe", "Brother Firetribe", "ACDC", "Republic", "Queen", "Sing Sing", "Pokolgép",
           "Sex Pistols", "Avril Lavigne", "Wheatus", "Alvin És A Mókusok", "Tankcsapda", "Depeche Mode",
           "Gary Numan", "Visage", "Green Day", "Offspring", "Good Charlotte", "HétköznaPI CSAlódások",
           "Cutie", "Black Sabbath", "Metallica", "Ossian", "Domain", "Lordi", "Hammerfall",
           "Apocalyptica", "Marilyn Manson", "Drowning Pool", "Evanescence", "Kárpátia", "Leander Kills",
           "Northern Kings", "Cserháti Zsuzsa", "Christina Aguilera", "Michael Jackson", "Zámbó Jimmy",
           "Justin Timberlake", "Madonna", "Black Eyed Peas", "Gnaris Barkley", "Beyonce Ft Shakira",
           "Jennifer Lopez", "Whitney Houston", "V-Tech", "Pintér Béla", "James Brown",
           "Kc & Sunshine Band", "Wild Cherry", "Mezzoforte", "Van Mccoy", "Gloria Gaynor",
           "Donna Summer", "Boney M", "Village People", "Neoton Família", "Máté Péter", "Back Ii Black",
           "Szűcs Judith", "Madonna", "Robbie Williams", "Britney Spears", "Spice Girls", "Baby Sisters",
           "Backstreet Boys", "Hip Hop Boys", "Ace Of Base", "Pa-Dö-Dő", "Cardigans", "Anastacia",
           "Vénusz", "Delfin Hangstúdió", "Sugarhill Gang", "2pac & Dr. Dre", "Eminem", "Rapülők",
           "Sub Bass Monster", "Coolio", "50 Cent", "Snoop Dogg", "DMX", "Notorious B.i.g. Feat. Pam",
           "Gorillaz", "Animal Cannibals", "Sir Mix-A-Lot", "Bananarama", "Kylie Minogue",
           "Right Said Fred", "Lenka", "Aqua", "Ufo", "Happy Gang", "Vengaboys", "Mr. President",
           "4F-Club", "Squeeze", "Ámokfutók", "Cartoons", "Delia Derbyshire", "Hot Butter",
           "Tangerine Dream", "Giorgio Moroder", "Jean Michel Jarre", "Kraftwerk", "Aphex Twin",
           "Daft Punk", "Presser Gábor", "Orbital", "P. R. Computer", "Ylvis", "Jean Jacques Perrey",
           "Technotronic", "Run D.m.c. Vs. J. Nevins", "Nightcrawlers", "2 Eivissa", "Daft Punk",
           "Armand Van Helden", "Alcazar", "Fatboy Slim", "Wamdue Project", "Inner City", "Maxx",
           "Madonna", "Kenny Dope Presents The Bucketheads", "Groove Coverage", "Safri Duo", "Avicii",
           "David Guetta Feat. Kelly Rowland", "ATB", "Eric Prydz", "Robert Miles", "Three Drives",
           "Barthezz", "Kozmix", "Soerii & Poolek", "Náksi Vs. Brunner", "Kerozin", "New Order",
           "Gary Numan", "A Flock Of Seagulls", "Yazoo", "Yello", "Real Life", "Pet Shop Boys",
           "Első Emelet", "Ákos", "Soft Cell", "My Mine", "Talk Talk", "GM49", "Apollo 440", "Prodigy",
           "Tatu", "Dj Fresh", "M Beat Feat. General Levy", "Amon Tobin", "J-Cut & Kolt Siewerts",
           "Vad Fruttik", "Kelemen Kabátban", "Kosheen", "Pendulum", "Neo feat. Dancshow", "Himmel",
           "And One", "Apoptygma Berzerk", "Assemblage 23", "Nik Page", "Front Line Assembly",
           "Marilyn Manson", "Aphex Twin", "Kmfdm", "Eisenfunk", "Rammstein", "Fantomas",
           "Bonanza Banzai", "Escalator", "Art Of Noise", "Paul Hardcastle", "Koop", "Julee Cruise",
           "Boards Of Canada", "Vangelis", "Jan Hammer", "Enya", "Mike Oldfield", "Mecano", "Enigma",
           "Shpongle", "Dobos Attila", "Santana", "Las Ketchup", "Los Del Rio", "Paradiso",
           "Gipsy Kings", "Eros Ramazotti", "Enrique Iglesias", "Ricky Martin", "Fiesta", "Desperado",
           "Paola & Chiara", "Chelo", "Delhusa Gjon", "Beach Boys", "Kaoma", "Harry Belafonte",
           "Carrapicho", "Los Lobos", "Vaya Con Dios", "Wes", "Afric Simone", "Velile & Safri Duo",
           "Milk & Sugar Feat. Miriam Makeba", "Shakira", "Dubem K x TboySimple", "Fekete Pákó",
           "Sister Nancy", "Musical Youth", "Bob & The Wailers", "Laid Back", "Ub 40", "Big Mountain",
           "Eek-A-Mouse", "Manu Chao", "Ladánybene 27", "Irie Maffia", "Alpha Blondy", "Belga",
           "Copy Con", "Aradszki László", "Szécsi Pál", "Kaczor Feri", "Lagzi Lajcsi", "Tekknő",
           "Dupla Kávé", "Mario", "Bódi Guszti & Lajcsi", "Emir Kusturica", "Ivan Mladek", "Gipsy Casual",
           "Nótár Mary", "Bohemian Betyars", "Tarkan", "Arash Ft. Rebecca", "Panjabi", "Arash",
           "Cheb Khaled Feat. Cameron Cartio", "Daler Mehndi", "Ylvis", "Barobax", "Saad Lamjarred", "The Hu",
           "Osmanlı Metal", "Ajnad Media Foundation", "Szarka Tamás", "Cusco", "Moya Brennan", "Era", "Enya",
           "Leo Rojas", "Corvus Corax", "Wardruna", "Hevia", "Nox", "Crystal", "Besh O Drom", "Kaláka", "Laár András",
           "Gotye", "The Caesars", "White Town", "Moby", "Fatboy Slim", "Sonique", "Depeche Mode", "Tanita Tikaram",
           "Peter, Bjorn & John", "Anima Sound System", "Heaven Street Seven", "Honeybeast", "Quimby",
           "Aerosmith And Run Dmc", "Lenny Kravitz", "Gerry Rafferty", "Aswad", "Irie Maffia", "Baha Men", "Roxette",
           "Red Hot Chilli Peppers", "Zanzibár", "Pink", "Jazz+Az", "Spice Girls", "United",
           "Susanne Vega", "Yonderboi", "Zagar", "The Bird And The Bee", "In Grid", "Doop",
           "Caravan Palace", "Bart & Baker", "Yolanda Be Cool", "Tape Five", "Devin Townsend Project",
           "V Is For Villains", "Diablo Swing Orchestra", "Nightwish", "Powerwolf", "Epica",
           "Korpiklaani", "Faun", "Paddy and the Rats", "Linkin Park", "Papa Roach", "Pod", "Celldweller",
           "Disturbed", "Zardonic and  Voicians", "Megus", "Napoleon Xiv", "Weird Al Yankovic",
           "Galla Miklós", "Rózsaszín Pitbull", "Méhek", "Belga", "Kistehén", "Kovbojok",
           "Irigy Hónaljmirigy", "Pamkutya", "The Lone Slim Shady (Explicit)", "DJ Cummerbund",
           "Slayer and Wham!", "Knife Party", "Skrillex", "Wolfgang Gartner", "Miracle Musical",
           "MiatriSs", "SOPHIE", "Macintosh Plus", "Anamanaguchi", "Yung Bae", "David Hasselhoff",
           "The Weeknd", "Quixotic", "OpenAI Jukebox"]


titles = ["Song Of Seikilos", "Dies Irae", "Oh Susana", "Az Ördög Útja", "Om Mani Padme Hum",
          "Hare Krishna", "Levan Polkka", "Drunken Sailor", "Johnny I Hardly Knew Ye", "Regősének",
          "Indulj El Egy Úton", "Tavaszi szél", "Bad Romance (Bardcore Cover)", "Toccata E Fuga",
          "Surprise (Symphony no. 94)", "7-Th Symphony", "Fifth Symphony", "Hanabera", "Bolero",
          "Wedding March", "Hungarian Dance No. 5", "O Fortuna", "Rigoletto", "Hungarian Rhapsody 2",
          "Gran Vals", "Szomorú Vasárnap", "The Entertainer",
          "It Don't Mean A Thing (If It Ain't Got That Swing)", "What A Wonderful World",
          "Strangers In The Night", "Lollipop", "Nem Vagyok Én Apáca", "Tequila", "Comment Te Dire Adieu",
          "Soul Bossa Nova", "The Girl From Ipanema", "Nekem A Balaton..", "Csinibaba",
          "János legyen fenn a János-hegyen", "La Marseillaise, French National Anthem",
          "Kommunista Internacionálé", "Somewhere Over The Rainbow", "Chi Mai (A Profi)", "Axel F.",
          "Beezleboss", "Boldog Születésnapot", "Micimackó", "Minikoncert", "Malév Reklám Zenéje",
          "Song Of The Second Moon", "Opus No. 1 (Cisco Hold Music)", "Windows 95 Startup Sound", "Mannish Boy",
          "Ring Of Fire", "Dédapám", "Levél A Távolból", "The Blue Cafe", "You Can Leave Your Hat On",
          "Jég Dupla Whiskyvel", "Elhagyom A Várost", "Wanted Dead Or Alive", "Hey Joe", "The Wanderer",
          "Postakocsi", "The Lumberjack", "Rock Around The Clock", "Johnny B. Goode", "Jail House Rock",
          "Csavard Fel A Szőnyeget", "Love Me Do", "I Got Life", "I'm A Believer",
          "Jelszó-Love, Szeretet", "Petróleum Lámpa", "House Of The Rising Sun", "California Dreamin'",
          "I Get Around", "Nyugi Doki", "We Didnt Start The Fire", "Paint It Black", "Runaway Train",
          "Balatoni Nyár", "I'll Be There For You", "I Am The Warrior", "Kickstart My Heart",
          "Game They Call Love", "Big Gun", "16 Tonna Fekete Szén", "Don't Stop Me Now", "Halál A Májra",
          "Gép-Induló", "God Save The Queen", "Girlfriend", "Teenage Dirtbag", "Bizalom",
          "A Legjobb Méreg", "A Question Of Time", "Are 'friends' Electric", "Fade To Grey",
          "Basket Case", "The Kids Aren't Alright", "Lifestyles Of The Rich And Famous", "Csaló Manó",
          "Akkor is", "War Pigs", "Enter Sandman", "Éjféli Lány", "Don't Pay The Ferryman",
          "Hard Rock Hallelujah", "Hearts On Fire", "Drive", "This Is Halloween", "Bodies",
          "Bring Me To Life", "Örökségem", "Kicsiny Falum", "Take On Me", "Boldogság, Gyere Haza",
          "The Voice Within", "Will You Be There", "Egyszer Megjavulok Én", "Rock Your Body",
          "Time Stood Still", "Wheres Is The Love", "Crazy", "Beautiful Liar", "Get Right",
          "I Will Always Love You", "Vele Minden Jó", "Soha Se Nézd", "I Feel Good",
          "That's The Way (I Like It)", "Play That Funky Music White Boy", "Garden Party", "The Hustle",
          "I Will Survive", "Hot Stuff", "Ma Baker", "Macho Men", "220 Felett",
          "Zene Nélkül Mit Érek Én", "Szerelembomba", "Táncolj Még", "Beautiful Stranger", "Millennium",
          "Toxic", "Say You'll Be There", "Szeresd A Testem Baby", "Larger Than Life", "Megbántottak",
          "The Sign", "Azt Csinálok, Amit Én Akarok", "Lovefool", "Paid My Dues", "Régi Nyár",
          "SZTE Újra", "Rapper's Delight", "California Love", "The Real Slim Shady", "Lesz Még Rosszabb",
          "Pörög A Fekete Lemez", "Gangsta's Paradise", "21 Questions", "Smoke Weed Everyday",
          "Party Up In Here", "Hypnotize", "Clint Eastwood", "Budapest Nyáron", "Baby Got Back", "Venus",
          "The Loco Motion", "Dont Talk - Just Kiss", "The Show", "Roses Are Red", "Napolaj",
          "Fiatal Szerelem", "Shalala Lala", "Coco Jambo", "Tanga", "Sweet Kisses", "Szomorú Szamuráj",
          "Witch Doctor", "Doctor Who Original Theme", "Popcorn", "Choronzon", "The Chase", "Oxygene 4",
          "Trans-Europe Express", "Window Licker", "Robot Rock", "La Baletta No. 2", "Chime",
          "Jól Hangolt Számítógép", "Ytterst På Tissen", "Brazilian Flower", "Pump The Jam",
          "It's Like That", "Push The Feeling On", "Oh La La", "One More Time", "You Don't Know Me",
          "Crying At The Discotheque", "Funk Soul Brother", "King Of My Castles", "Good Life",
          "Get Away", "Hung Up", "The Bomb", "Poison", "Played A Live", "Wake Me Up",
          "When Love Takes Over", "The Summer", "Call On Me", "Fable",
          "Greece 2000 (Paul Oakenfold Mix)", "On The Move", "Kozmix a Házban", "Valahol messze",
          "Nézz Az Ég Felé", "Nelli Az Elefánt", "Blue Monday", "Cars", "I Ran", "Don't Go", "Oh Yeah",
          "Send Me An Angel", "Domino Dancing", "A Film Forog Tovább", "Indiántánc", "Tainted Love",
          "Hypnotic Tango", "It's My Life", "Elektromos gyalogos (2018)", "Ain't Talking Bout Dub",
          "Mindfields", "Not Gonna Get Us", "Gold Dust", "Incredible", "Nightlife",
          "The Flute Tune (Soulpride Remix)", "Nekem Senkim Sincsen", "Maradjatok Gyerekek (Feat. Eckü)",
          "Empty Skies", "Set Me On Fire", "Videomania", "Terézanya", "Steine Sind Steine",
          "A Battle For The Crown", "Ground", "Dein Kuss", "Mindphaser", "This Is The New Shit",
          "Come To Daddy", "Free Your Hate", "Pong", "Engel", "Rosemary's Baby", "Kihalt Minden",
          "Hívom A Múltat (Mix)", "Moments In Love", "Lazy Days", "Summer Sun (Markus Enochson Remix)",
          "Falling (Twin Peaks Theme)", "Nothing Is Real", "Opéra Sauvage", "Crockett's Theme",
          "Orinoco Flow (Sail Away)", "To France", "Hijo de la Luna", "Innocence",
          "Around The World In A Tea Daze", "Magyarok Vilaghimnusza", "Maria Maria",
          "The Ketchup Song (Aserejé)", "Macarena", "Bailando", "Bamboleo", "Piu Bella Cosa",
          "Rhythm Divine", "The Cup Of Life", "Hola Mi Amor", "Táncolj", "Vamos A Bailar", "One Heart",
          "Nika Se Perimeno", "Kokomo", "Lambada", "Matilda", "Tic Tic Tac", "La Bamba", "Nan Neh Nan",
          "Alane", "Hafanana", "Helele", "Pata Pata", "Waka Waka", "Buzadara", "Mayo", "Bam Bam",
          "Pass The Dutchie", "I Shot The Sheriff", "Sunshine Reggae", "Kingston Town",
          "Oh Baby I Love Your Way", "Isn't Life A Trip", "Bongo Bong", "Kell Egy Ház",
          "Bacardi Cola (feat. MC Kemon)", "Seba Allah Ye", "Boros", "Windózjó",
          "Nem Csak A Húszéveseké A Világ", "Egy Szál Harangvirág", "Hajmási Péter",
          "Majd Ha Nékem Sok Pénzem Lesz", "Csujjogató", "Bocsássa Meg Nekem A Világ", "Amikor A Szívem",
          "Aranyeső", "Djinji Rindji Bubamara", "Jozin z Bazin", "Balans Prala", "Rázd Meg",
          "Megjöttek A Fiúk", "Simarik", "Temptation", "Mundian To Bach Ke", "Boro Boro", "Henna",
          "Tunak Tunak Tun", "Mr. Toot", "Soosan Khanoom", "Lm3allem", "Yuve Yuve Yu", "Dombıra (Remix)",
          "Dawlat al-Islam Qamat (Dawn Has Appeared)", "Tündértakaró", "Flying Condor", "River", "Ameno", "Adiemus",
          "El Condor", "Totentanz", "Helvegen", "Busindre Reel", "Tűztánc", "Két Utazó", "Meggyújtom A Pipám",
          "Dél Keresztje", "Tűzhimnusz", "Somebody That I Used To Know (Feat.  Kimbra)", "Jerk It Out", "Your Woman",
          "Lift Me Up", "Right Here Right Now", "Sky", "Just When I Lose Myself", "Twist In My Sobriety",
          "Young Folks", "Csinálj Gyermeket!", "Dél-Amerika", "A Legnagyobb Hős", "Most Múlik Pontosan",
          "Walk This Way", "Fly Away", "Baker Street", "Don't Turn Around", "Hands In The Air",
          "Who Let The Dogs Out", "The Look", "Scar Tissue", "Szerelemről szó sem volt", "Stupid Girls",
          "Helló Édes", "Who Do You Think You Are", "Hófehér Jaguár", "Tom's Diner", "Pabadam",
          "Wings Of Love", "Again And Again", "Vive Le Swing", "Doop", "Dragons",
          "Istanbul (Not Constantinople)", "We No Speak Americano", "Bad Boy Good Man", "Bad Devil",
          "Pink Elephants On Parade", "Ballrog Boogie", "Phantom Of The Opera", "Sanctus Dominus",
          "Cry For The Moon", "Vodka", "Tanz Mit Mir", "Pilgrim On The Road", "Papercut", "Last Resort",
          "Youth Of The Nation", "Tough Guy (Tim Ismag Remix)", "Stricken", "Bring Back The Glory",
          "Bad Monday (Blue Monday + Bad Apple, Feat. Emnily)", "They're Coming To Take Me Away",
          "White & Nerdy", "Dallas", "Ne Szívjál Füvet", "Barbi Dal", "Gépkocsi", "Szájbergyerek",
          "Télapó", "Numerakirály", "Aranybula", "Caravan Palace Vs. Eminem (Mashup)",
          "Play That Funky Music Rammstein", "Tropicana Death Ensemble", "Internet Friends",
          "Rock N' Roll", "Illmerica", "The Mind Electric", "Take Me!", "Faceshopping", "420",
          "Miku (feat. Hatsune Miku)", "Welcome to the Disco", "True Survivor", "Blinding Lights",
          "Dust To Dust", "Never Gonna Give You Up"]


def match_answer(answer, genre, track, is_artist=False):
    return SequenceMatcher(None, answer.lower(), get_prompt(genre, track, is_artist).lower()).ratio()


def get_prompt(genre, track, is_artist=False):
    track_code = genre * 13 + track
    return artists[track_code] if is_artist else titles[track_code]


def get_genre(genre):
    return genres[genre]
